### ISSUE TITLE
How can I make the color static?

### ISSUE THREAD

**Issue by furatamasensei** [knezzz/RandomColor#8]
I've just implemented this package on my app, but It keep changing its color. Please see this recording.

![ezgif-2-f063ccb33a08](https://user-images.githubusercontent.com/42239243/89942864-7c096280-dc47-11ea-86d0-b91b426bacd5.gif)

Is there any way to prevent this? *Please note that the `Title` field has nothing to do with the participant chips.

**Comment by knezzz** [comment]
Hey yeah that is possible :D

You have to use random with same seed, it would help to see your code but idea is this:

```dart
RandomColor _rand = RandomColor(0); 
_rand.randomColor();
/// We set up RandomColor with seed 0 above.
/// This guarantes us that [randomColor] will always produce exact same color, 
/// and if you call it multiple times then the same color sequance will be generated.
```

Hope that helps :) If not please share part of code where you are using the lib and how you are using it. So I could help better :) 

p.s. You can also hash participants and use that as seed, so each participant will always have that same color assigned to them.

edit: Oh and also, they are changing because whole screen is getting rebuilt when you type, (new colors are getting generated) some optimization would also fix that.

**Comment by furatamasensei** [comment]
Cool, using seed works for now. Thanks!

```dart
final RandomColor _randomColor = RandomColor(participant.id);
final Color _chipBackgroundColor = _theme == ThemeMode.light
    ? _randomColor.randomMaterialColor().shade50
    : _randomColor.randomMaterialColor().shade900;
```

edit: I think it should be written in the docs.
